### ISSUE TITLE
basic_example.py fails due to an unexpected keyword argument `modes` 

### ISSUE THREAD

**Issue by GeorgySk** [mikekatz04/GBGPU#6]
When running the _basic_example.py_, I'm getting the following error:
```
Traceback (most recent call last):
  File "/opt/project/examples/basic_example.py", line 82, in <module>
    A_inj, E_inj = gb.inject_signal(
  File "/opt/project/gbgpu/gbgpu.py", line 919, in inject_signal
    self.run_wave(*args, **kwargs)
TypeError: run_wave() got an unexpected keyword argument 'modes'
```

**Comment by mikekatz04** [comment]
This is an old script that should have been removed. It is now removed. Refer to the tutorial.
